# Generated by Django 3.2.13 on 2023-02-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_postions_nothing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postions',
            name='nothing',
        ),
    ]
