# Generated by Django 3.2.13 on 2023-02-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_alter_contestant_aspirantbio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='ballotbox',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='member',
        ),
        migrations.DeleteModel(
            name='BallotBox',
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
    ]
